spring:
    datasource:
        url: jdbc:mysql://localhost:3306/daily-expenses
        username: root
        password: password
        
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL5Dialect
            